- name: Configuração Startup Financas API
  hosts: api
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar PHP
      apt:
        name: php
        state: present

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Clonar repositório
      git:
        repo: 'https://github.com/Alison4kk/currency-online-api.git'
        dest: /home/ubuntu/api
        version: main

    - name: Rodar API
      shell: |
        cd /home/ubuntu/api
        nohup php -S 0.0.0.0:8000 index.php &