name: CI - Currency Online API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Build e rodar testes
        run: |
          docker-compose up -d --build
          sleep 5
          docker-compose run --rm api php testes/test_converter.php